export const STORE_ADD_REQUEST = "STORE_ADD_REQUEST";
export const STORE_ADD_SUCCESS = "STORE_ADD_SUCCESS";
export const STORE_ADD_FAIL = "STORE_ADD_FAIL";


export const STORE_GET_REQUEST = "STORE_GET_REQUEST";
export const STORE_GET_SUCCESS = "STORE_GET_SUCCESS";
export const STORE_GET_FAIL = "STORE_GET_FAIL";